import * as fs from 'node:fs';
import palettes from './palettes.js';

const HEADER =
  '/* Autogenerated by https://github.com/momentum-mod/styling/blob/main/colors/src/export.js */\n';

const safeKey = (str) => (/^\w+$/.test(str) ? str : `'${str}'`);
console.log('Generating Tailwind (CJS)');
fs.writeFileSync(
  '../colors-tailwind-vars.cjs',
  HEADER +
    'module.exports = {\n' +
    palettes
      .map(
        ({ paletteName, swatches }) =>
          `  ${safeKey(paletteName)}: {\n` +
          swatches
            .flatMap(({ name, color }) => `    ${safeKey(name)}: '#${color}',`)
            .join('\n') +
          '\n  },'
      )
      .join('\n') +
    '\n}\n'
);

console.log('Generating Tailwind (ESM)');
fs.writeFileSync(
  '../colors-tailwind-vars.mjs',
  HEADER +
    'export default {\n' +
    palettes
      .map(
        ({ paletteName, swatches }) =>
          `  ${safeKey(paletteName)}: {\n` +
          swatches
            .flatMap(({ name, color }) => `    ${safeKey(name)}: '#${color}',`)
            .join('\n') +
          '\n  },'
      )
      .join('\n') +
    '\n}\n'
);

console.log('Generating CSS');
fs.writeFileSync(
  '../colors-css-vars.css',
  HEADER +
    ':root {\n' +
    palettes
      .map(({ paletteName, swatches }) =>
        swatches
          .flatMap(
            ({ name, color }) => `  --${paletteName}-${name}: #${color};`
          )
          .join('\n')
      )
      .join('\n\n') +
    '\n}\n'
);

console.log('Generating Sass');
fs.writeFileSync(
  '../colors-sass-vars.scss',
  HEADER +
    palettes
      .map(({ paletteName, swatches }) =>
        swatches
          .flatMap(
            ({ name, color }) => `$${paletteName}-${name}: #${color} !default;`
          )
          .join('\n')
      )
      .join('\n\n') +
    '\n'
);

console.log('Done :D');
